services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./backend/public:/public
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - ./frontend/public:/app/public
  #   depends_on:
  #     - backend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   networks:
  #     - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    # entrypoint: 
    #   /frontend/start.sh
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: